### ISSUE TITLE
Convene Interest

### ISSUE THREAD

**Issue by ezampino** [data2health/leaf-edw#10]
Compile interest from [survey](https://redcap.iths.org/surveys/?s=7XL99874JT) and solicit interest

Send one page document and intro email inviting to community.

**Comment by mellybelly** [comment]
for project engagement tracking, it would be great to see the survey, who it was sent to when, and what the responses looked like. @cgcook @jmcmurry

**Comment by mellybelly** [comment]
also @LisaOkeefe1

**Comment by ezampino** [comment]
We are utilizing information from this survey sent out in January: https://redcap.iths.org/surveys/?s=7XL99874JT . 

I do not want to post results as it contains email addresses.

**Comment by mellybelly** [comment]
Ah ok. no prob, just wanted to make sure we didn't miss any new survey - probably should be coordinated since lots of CD2H group need that sort of thing and need to be careful not to spam.

**Comment by ezampino** [comment]
Agreed! This catch probably will be a benefit in the future no doubt!

**Comment by jmcmurry** [comment]
If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by jmcmurry** [comment]
ps. This just in: a coordinated email will be going out for all projects; stay tuned.

**Comment by jmcmurry** [comment]
Baseline email was sent; all ok to proceed with project - specific communications.
