### ISSUE TITLE
Questions from UChicago about Leaf Validation

### ISSUE THREAD

**Issue by ezampino** [data2health/leaf-edw#28]
Please answer [these](https://docs.google.com/document/d/1zLNTzahVL2ReasvPLmG1Yw6MhomlcdnUWXT9L8JzwfQ/edit) in a timely manner and cc: me.

Thanks!

**Comment by ndobb** [comment]
The questions have been answered and UChicago is satisfied (confirmed over our biweekly developer meeting).
