### ISSUE TITLE
Status update for JHU Pilot

### ISSUE THREAD

**Issue by ezampino** [data2health/leaf-edw#31]
Status update on where JHU is for the fall meeting.

**Comment by ndobb** [comment]
Current status:
- Leaf pilot deployment has been given the full go ahead at JHU from the MS Clinical Leadership per Paul's email on 7/11.
- Paul has developed Python scripts that will be usable by the Leaf community to dynamically configure Leaf concepts based on database data. To date they've used this method to create 700+ concepts, which are being used on the Multiple Sclerosis Leaf instance at JHU.

When to open Leaf up to users, as well as when to expand Leaf to other JHU Centers of Excellence is ultimately up to JHU and as their partner we'll continue to advise and help. Given that the JHU MS precision medicine Leaf instance is up-and-running and querying actual clinical data, as well as the positive early feedback from JHU MS leadership and Paul's great work and contributions, I think we can set this milestone to complete.
